language: go
env:
  - GO15VENDOREXPERIMENT=1
go:
  - 1.5
install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo
  - glide up
os:
  - linux
  - osx
script:
  - make test
  - make build
