language: go
go:
  - 1.13.x
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
before_install:
  - "[[ $TRAVIS_OS_NAME != osx ]] || brew list bash || brew install bash"
  - "[[ $TRAVIS_OS_NAME != osx ]] || brew list coreutils || brew install coreutils"
install:
  - make depend
script:
  - make test
  - make build
  # Deploy build result to s3
  - export AWS_ACCESS_KEY_ID=AKIAIX3L4RHHIREAHABQ
  - export AWS_SECRET_ACCESS_KEY=${RSBIN_KEY}
  - "[[ -z $AWS_SECRET_ACCESS_KEY ]] || make upload"
