clone_folder: C:\projects\go\src\github.com\douglaswth\right_st
environment:
  CYGWIN: nodosfilewarning
  GOPATH: C:\projects\go
  GO15VENDOREXPERIMENT: 1
install:
  - appveyor SetVariable -Name PATH -Value "%GOPATH%\bin;%PATH%;C:\Ruby21-x64\DevKit\mingw\bin;C:\cygwin\bin"
  - make depend
build_script:
  - make
test_script:
  - make test
artifacts:
  - path: right_st.exe
