# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


required = ["github.com/rlmcpherson/s3gof3r/gof3r", "github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/douglaswth/rsrdp"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/rightscale/rsc"

[[constraint]]
  branch = "master"
  name = "github.com/tonnerre/golang-pretty"

[prune]
  unused-packages = true
